
#include <string.h>
#include <stdio.h>
#include <stdarg.h>

int main(int argc, const char *argv[]) {
  printf("/* Generated by bin2c v1.0.2; Copyright (c) 2007 Gustav Munkby */\n");
  bool header;
	const char *name;
  switch (argc) {
	case 2:
			header = false;
		  name = argv[1];
			break;
  case 3:
		if (strcmp(argv[1], "-h") == 0) {
			header = true;
			name = argv[2];
			break;
		}
		// Fallthrough
	default:
		fprintf(stderr, "Usage: bin2c [-h] name\n");
		return 1;
	}

	unsigned int size = 0;
	if (header) {
		printf("#ifdef __cplusplus\nextern \"C\" {\n#endif\n");
		printf("extern \"C\" const unsigned char %s[];\n", name);
	} else {
		printf(       "const unsigned char %s[] = {\n", name);
		int c;
		bool indent = true;
		while ((c = getchar()) != EOF) {
		  if (indent) {
				indent = false;
				printf("\t");
			}
			printf("0x%02X, ", c);
			if (++size % 8 == 0) {
				indent = true;
				printf("\n");
			}
		}
		printf("\n};\n");
	}
	
	if (header) {
		printf("extern \"C\" const unsigned int %s_size;\n", name);
		printf("#ifdef __cplusplus\n}\n#endif\n");
	} else {
		printf(       "const unsigned int %s_size = %d;\n", name, size);
	}

 	return 0;
}
